// This file was generated by scripts/update_oauth_resources.sh
// Rerun scripts/update_oauth_resources.sh to update this file
// Please do not edit manually
// Filled in with real app versions
pub const _IOS_APP_VERSION_LIST: &[&str; 1] = &[""];
pub const ANDROID_APP_VERSION_LIST: &[&str; 3] = &["Version 2026.22.0/Build 2622090", "Version 2026.23.0/Build 2623001", "Version 2026.24.0/Build 2624051"];
pub const _IOS_OS_VERSION_LIST: &[&str; 1] = &[""];
